version: '3'
services: 
  streamlit_apps:
    container_name: streamlit_application
    image: "linhnt47/streamlit_tableview:v1.0"
    ports: 
      - 8501:8501 
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_DIR=/SVTECH-Junos-Automation/Python-Development/streamlit_apps/optic_data
      - VAR_PATH=/root/default_variable.yml
    volumes:
      - /var/tmp:/SVTECH-Junos-Automation/Python-Development/streamlit_apps/optic_data
