# docker buildx build --build-arg git_token=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 --build-arg user_email=thihuongphung09@gmail.com --build-arg user_name=huongpt11 -t huong_test:v1 . --no-cache
version: '3'
services: 
  streamlit_apps:
    container_name: streamlit_application
    image: "huong_test:v1"
    ports: 
      - 8501:8501 
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VAR_DIR=/SVTECH-Junos-Automation/Python-Development/streamlit_apps
      - VAR_PATH=/SVTECH-Junos-Automation/Python-Development/streamlit_apps/default_variable.yml
    volumes:
      - default_variable:/SVTECH-Junos-Automation/Python-Development/streamlit_apps
### monut VAR_DIR in container to local host: /var/lib/docker/volumes/streamlit_apps_default_variable/_data
volumes:
  default_variable: